### ISSUE TITLE
混用本模组和Gregic Energistics模组的multiblock parts出现未期待的行为

### ISSUE THREAD

**Issue by YiRanMushroom** [liansishen/GTMThings#11]
在尝试使用本模组的me_output_buffer，与Gregic Energistics中ME Stocking Input Hatch时，即使在该模组中的输入仓内标记对应流体，也无法正确启动配方。

我在测试时使用电解盐水配方，发现无法启动。

如果添加一个GregTech Modern的输入仓，则配方可以启动，尽管其中不存在流体。

我认为也有可能是Gregic Energistics的问题，但是使用其他输出设备时依然正常，所以我选择在此处创建issue。

**Comment by liansishen** [comment]
经测试，无论是否使用me_output_bufer都存在该问题，甚至不添加gtmthings模组。
尝试debug GE，发现不加GTM原版输入仓，就无法进入stocking hatch的handleRecipeInner
该问题可尝试提交至GE的issue
