### ISSUE TITLE
无线激光源仓将能量输入无线电网的功率有误

### ISSUE THREAD

**Issue by FwFeiVan** [liansishen/GTMThings#2]
build15中

无线激光源仓将EU输入无线电网的功率始终为该仓的功率，并非实际接受到的功率。
如图，整个存档只有这一个无线激光源仓(16384A MAX)与这一台LV内燃机。LV内燃机输入0.5A HV的电进入有源，
并且激光源仓显示缓存256EU。

然而无线显示屏显示输入功率16384A MAX，并且总电量明显不是以HV该有的速度增加，增加速度应该就是16384A MAX EU/t
![11](https://github.com/liansishen/GTMThings/assets/159519096/ae7dc5f8-badd-45c3-a148-cc56b5246f97)
![22](https://github.com/liansishen/GTMThings/assets/159519096/6a312d1c-906c-4585-a054-5ef404743075)
![33](https://github.com/liansishen/GTMThings/assets/159519096/116fae8a-fb4f-4e53-baa2-bf5814e430d6)

此外，我若停止小内燃的发电，则无线监视器显示电网无EU输入。
![44](https://github.com/liansishen/GTMThings/assets/159519096/055a6ee1-aa98-436b-8690-787496da1214)

**Comment by liansishen** [comment]
已修复
