### ISSUE TITLE
无线流体覆盖版导致崩溃性问题

### ISSUE THREAD

**Issue by Ypiaoyang** [liansishen/GTMThings#42]
![屏幕截图 2024-11-28 130803](https://github.com/user-attachments/assets/51d222f7-dcbe-40a3-bc81-b17824edcf55)
更新之后，进入世界将导致崩溃

**Comment by Ypiaoyang** [comment]
[错误报告-2024-11-28_12.49.42.zip](https://github.com/user-attachments/files/17943317/-2024-11-28_12.49.42.zip)

**Comment by liansishen** [comment]
试试这个版本
https://github.com/liansishen/GTMThings/actions/runs/12064301492

**Comment by liansishen** [comment]
Fix in #43
