### ISSUE TITLE
java.lang.ExceptionInInitializer Error

### ISSUE THREAD

**Issue by scorevi** [liansishen/GTMThings#44]
![image](https://github.com/user-attachments/assets/0ae34b1d-720c-4e3e-869b-81524a867006)
I have an issue, it's not launching
Modpack: ATM9
[2024-12-03-6.log](https://github.com/user-attachments/files/17989040/2024-12-03-6.log)

**Comment by scorevi** [comment]
[crash-2024-12-03_15.49.00-fml.txt](https://github.com/user-attachments/files/17989208/crash-2024-12-03_15.49.00-fml.txt)

**Comment by liansishen** [comment]
you may enable the hightier in config file.

**Comment by scorevi** [comment]
in the GTCEu config? Okay, I'll try.

**Comment by liansishen** [comment]
Fix in #43 
you can use version 1.3.8 at curseforge 
or download from [here](https://github.com/liansishen/GTMThings/releases/tag/1.3.8-build_40)
