### ISSUE TITLE
与1.6.0版本的GTM一起使用时报错

### ISSUE THREAD

**Issue by Spear-mini-submarine** [liansishen/GTMThings#46]
[crash-2024-12-22_15.13.05-fml.txt](https://github.com/user-attachments/files/18221058/crash-2024-12-22_15.13.05-fml.txt)

**Comment by liansishen** [comment]
gtm1.6版本破坏性更新，请等待适配

**Comment by liansishen** [comment]
已适配，请更新1.3.9版本
